# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-09 23:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('info', models.TextField()),
                ('info_pt', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='init/img/communities/')),
            ],
            options={
                'verbose_name_plural': 'Communities',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('title_pt', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('content_pt', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='init/img/news/')),
            ],
            options={
                'verbose_name_plural': 'News',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('info', models.TextField()),
                ('info_pt', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='init/img/projects/')),
            ],
            options={
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('linkedin', 'Linked In'), ('twitter', 'Twitter')], max_length=100)),
                ('url', models.CharField(max_length=400)),
                ('is_from_branch', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Social Networks',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_year', models.IntegerField()),
                ('end_year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Team Members',
            },
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ieee_contact', models.EmailField(max_length=254, null=True, unique=True)),
                ('image', models.ImageField(upload_to='init/img/volunteers/')),
                ('socials', models.ManyToManyField(blank=True, to='app.SocialNetwork')),
            ],
        ),
        migrations.AddField(
            model_name='teammember',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Volunteer'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Team'),
        ),
        migrations.AddField(
            model_name='projects',
            name='coordinator',
            field=models.ManyToManyField(blank=True, to='app.Volunteer'),
        ),
        migrations.AddField(
            model_name='news',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='app.Tag'),
        ),
        migrations.AddField(
            model_name='community',
            name='chair',
            field=models.ManyToManyField(blank=True, related_name='chair', to='app.Volunteer'),
        ),
        migrations.AddField(
            model_name='community',
            name='vice_chair',
            field=models.ManyToManyField(blank=True, related_name='vice_chair', to='app.Volunteer'),
        ),
    ]
