# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-22 22:39
from __future__ import unicode_literals

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Initiative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('title_pt', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('content_pt', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InitiativeEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('title_pt', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('content_pt', models.TextField()),
                ('image', models.ImageField(upload_to=app.models.PathAndRename('img/partners'))),
                ('date', models.DateTimeField()),
                ('facebook', models.URLField(blank=True, null=True)),
                ('initiative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Initiative')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, null=True)),
                ('name', models.CharField(max_length=128)),
                ('image', models.ImageField(upload_to=app.models.PathAndRename('img/initiative_events/'))),
            ],
        ),
        migrations.AlterField(
            model_name='community',
            name='image',
            field=models.ImageField(blank=True, upload_to=app.models.PathAndRename('img/communities/')),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.PathAndRename('img/news/')),
        ),
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.ImageField(blank=True, upload_to=app.models.PathAndRename('img/projects/')),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='image',
            field=models.ImageField(upload_to=app.models.PathAndRename('img/volunteers/')),
        ),
        migrations.AddField(
            model_name='initiative',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Community'),
        ),
        migrations.AddField(
            model_name='initiative',
            name='partners',
            field=models.ManyToManyField(blank=True, null=True, to='app.Partner'),
        ),
    ]
