# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-12 23:46
from __future__ import unicode_literals

import app.models
import app.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20160927_0913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('title_pt', models.CharField(max_length=100)),
                ('pdf', models.FileField(upload_to=app.models.PathAndRename('pdf/newsletters'), validators=[app.validators.validate_if_is_pdf_file])),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Community')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='initiative',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.PathAndRename('img/initiative_events/')),
        ),
    ]
