# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-13 22:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170112_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 1, 13, 22, 51, 16, 599643, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
