# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-15 19:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_newsletter_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 15, 19, 35, 57, 861131, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
