# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-17 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_newsletter_publish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='newsletter_subscribe_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
