# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-13 17:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20170127_2159'),
        ('app', '0008_auto_20170125_2141'),
    ]

    operations = [
    ]
